name: stockaxis
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  dio: ^5.8.0+1
  dartz: ^0.10.1
  retrofit: ^4.4.2
  freezed_annotation: ^2.4.4
  go_router: ^14.8.1
  pretty_dio_logger: ^1.4.0
  http: ^1.3.0
  dropdown_button2: ^2.3.9
  html: ^0.15.5
  retrofit_generator: ^9.1.9
  freezed: ^2.5.8
  build_runner: ^2.4.15
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
